/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

// Most of these sidebars are automated.
// Each category is controlled by a "_category_.json" file in their respective directory.
// Individual category and page ordering is alphabetical by default but can be changed via their metadata, which is not always necessary.

const sidebars = {
  docs: [{ type: 'autogenerated', dirName: 'modules'}],
  Reference: [{ type: 'autogenerated', dirName: 'reference'}],
  Guides: [{ type: 'autogenerated', dirName: 'guides'}],
  Commands: [{ type: 'autogenerated', dirName: 'commands'}],
  Events: [
    "events/main",
    {Format: ["events/xml", "events/examples"],},
    "events/teams",
  ],
  Examples: [{type: 'autogenerated', dirName: 'examples'}],
};

export default sidebars;
